export const CHANGE_PRICE = "CHANGE_PRICE";
export const CHANGE_MODE = "CHANGE_MODE";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_DEFAULT_NAVBAR = "CHANGE_DEFAULT_NAVBAR";
export const CHANGE_DATE_RANGE = "CHANGE_DATE_RANGE";
