export const CHANGE_PRICE = "CHANGE_PRICE";
export const CHANGE_MODE = "CHANGE_MODE";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_GRAPHTYPE = "CHANGE_GRAPHTYPE";
export const CHANGE_COLORTYPE = "CHANGE_COLORTYPE";
