export const TOGGLE_DEVICE_SWITCH = 'TOGGLE_DEVICE_SWITCH'
export const FETCH_DATA_BEGIN   = 'FETCH_DATA_BEGIN';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const CHANGE_START_DATE = 'CHANGE_START_DATE'
export const CHANGE_END_DATE = 'CHANGE_END_DATE'
export const CHANGE_INTERVAL = 'CHANGE_INTERVAL'
export const CREATE_DEVICE_COLORS = 'CREATE_DEVICE_COLORS'