
/* DO NOT EDIT THIS FILE !!! */

import React from "react";
import ReactDOM from "react-dom";
import 'bootstrap';
import './scss/Main.scss';
import App from "./components/App/App";
import {HashRouter} from 'react-router-dom';

ReactDOM.render(
    <HashRouter>
      <App/>
    </HashRouter>,

    document.getElementById("root")
);

module.hot.accept();
